mongodb:
    image: mongo
    expose: 
     - 27017
    volumes:
     - /var/mongo/db:/data/db
    restart: always
katalog:
    image: joakimbeng/katalog
    expose:
     - 5005
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/katalog/data:/app/data
     - /var/katalog/nginx:/app/nginx
#     - /var/katalog/tpl:/app/tpl
    restart: always
sitewatcher:
    #image: joakimbeng/nginx-site-watcher
    build: github.com/jonaseck2/nginx-site-watcher.git
    expose:
     - 80
    volumes:
     - /var/katalog/nginx:/etc/nginx/sites-enabled:ro
    restart: always
api:
    build: github.com/Softhouse/laughing-batman.git
    links:
     - mongodb
    env_file: github_secret.env
    environment: 
     - KATALOG_VHOSTS=default/api
     - MONGO_HOST=mongodb
builder:
    build: github.com/Softhouse/flaming-computing-machine.git
    links:
     - mongodb
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
    env_file: github_secret.env
    environment:
     - MONGO_HOST=mongodb
    restart: always
googleauth:
    image: a5huynh/google-auth-proxy
    expose: 
     - 4180
    env_file: google_auth_proxy.env
    links:
     - sitewatcher
    command: --upstream=http://sitewatcher --http-address=0.0.0.0:4180 --cookie-https-only=false --redirect-url="http://xyz.softhouse.se/oauth2/callback" --google-apps-domain="softhouse.se"
    restart: always
proxy:
    image: nginx
    ports:
     - 80:80
    links:
     - googleauth
     - sitewatcher
    volumes:
     - proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - proxy/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    restart: always
